"""empty message

Revision ID: 04ba491e2337
Revises: 27b54beb4912
Create Date: 2022-10-07 21:56:10.841819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04ba491e2337'
down_revision = '27b54beb4912'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE publicationsource ADD VALUE 'CONSULTANT'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE publicationsource RENAME TO publicationsource_old")
    op.execute("CREATE TYPE publicationsource AS ENUM('times', 'RIA', 'RBC', 'BUH')")
    op.execute((
        "ALTER TABLE transactions ALTER COLUMN publicationsource TYPE publicationsource USING "
        "publicationsource::text::publicationsource"
    ))
    op.execute("DROP TYPE publicationsource_old")
    # ### end Alembic commands ###
