"""empty message

Revision ID: 27b54beb4912
Revises: 8c391eae81eb
Create Date: 2022-10-07 19:30:55.259779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27b54beb4912'
down_revision = '8c391eae81eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE publicationsource ADD VALUE 'BUH'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE publicationsource RENAME TO publicationsource_old")
    op.execute("CREATE TYPE publicationsource AS ENUM('times', 'RIA', 'RBC')")
    op.execute((
        "ALTER TABLE transactions ALTER COLUMN publicationsource TYPE publicationsource USING "
        "publicationsource::text::publicationsource"
    ))
    op.execute("DROP TYPE publicationsource_old")
    # ### end Alembic commands ###
