"""empty message

Revision ID: 58da1e326dd6
Revises: f621f3586bee
Create Date: 2022-10-08 20:50:13.186123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58da1e326dd6'
down_revision = 'f621f3586bee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic_info', sa.Column('topic_name_display', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topic_info', 'topic_name_display')
    # ### end Alembic commands ###
