"""empty message

Revision ID: 99615f987cda
Revises: f8a00c89a3b4
Create Date: 2022-10-07 14:34:28.010834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99615f987cda'
down_revision = 'f8a00c89a3b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE publicationsource ADD VALUE 'RIA'")
        op.execute("ALTER TYPE publicationsource ADD VALUE 'RBC'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE publicationsource RENAME TO publicationsource_old")
    op.execute("CREATE TYPE publicationsource AS ENUM('times')")
    op.execute((
        "ALTER TABLE transactions ALTER COLUMN publicationsource TYPE publicationsource USING "
        "publicationsource::text::publicationsource"
    ))
    op.execute("DROP TYPE publicationsource_old")
    # ### end Alembic commands ###
