"""empty message

Revision ID: 9fc4a26a11db
Revises: c3aa2521c835
Create Date: 2022-10-08 13:56:41.522817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fc4a26a11db'
down_revision = 'c3aa2521c835'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publications', sa.Column('tags', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publications', 'tags')
    # ### end Alembic commands ###
