"""empty message

Revision ID: e505fa3d66de
Revises: 58da1e326dd6
Create Date: 2022-10-09 01:33:07.640355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e505fa3d66de'
down_revision = '58da1e326dd6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE publicationsource ADD VALUE 'MY_BUSINESS'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE publicationsource RENAME TO publicationsource_old")
    op.execute("CREATE TYPE publicationsource AS ENUM('times', 'RIA', 'RBC', 'BUH', 'CONSULTANT')")
    op.execute((
        "ALTER TABLE transactions ALTER COLUMN publicationsource TYPE publicationsource USING "
        "publicationsource::text::publicationsource"
    ))
    op.execute("DROP TYPE publicationsource_old")
    # ### end Alembic commands ###
