FROM python:3.9

WORKDIR /app

RUN pip install --upgrade pip

COPY rec_engine/requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY rec_engine/ .
COPY api/src src

CMD python3 -m src_api.main
